/**
 * Represents a user in the system.
 * This is the core user model.
 */
export interface IUser {
  id: string; // Typically a UUID, generated by your database
  auth0Id: string; // The unique identifier from your authentication provider
  email: string; // User's email, should be unique
  name?: string; // Optional user name
  onboardingStatus: 'incomplete' | 'complete'; // To track if user has finished setup (e.g., linked an account)
  
  // Financial preferences
  defaultCurrency: string; // e.g., "USD", "EUR" (ISO 4217 code)
  timezone: string; // e.g., "America/New_York" (IANA time zone format)
}

/**
 * Stores user-specific settings and preferences.
 * This can be a separate table linked by userId.
 */
export interface IUserPreferences {
  userId: string; // Foreign key linking to the IUser table
  weeklyReport: boolean; // Opt-in for weekly email summaries
  taxRate?: number; // Optional personal tax rate for estimations
  businessHours?: [number, number]; // [startHour, endHour], e.g., [9, 17] for 9am to 5pm
}

/**
 * Represents a single financial transaction.
 */
export interface ITransaction {
  id: string; // Unique transaction ID
  userId: string; // Foreign key linking to the IUser table
  accountId: string; // Foreign key linking to the IAccount table
  plaidTransactionId: string; // The unique ID for this transaction from Plaid
  
  amount: number; // The transaction amount (positive for income, negative for expense)
  currency: string; // ISO 4217 code
  date: Date; // Use the Date object for easier manipulation
  
  merchant?: string; // The name of the merchant
  plaidCategory?: string[]; // Plaid's category hierarchy, e.g., ["Food and Drink", "Restaurants"]
  customCategory?: string; // A user-defined category to override Plaid's
  
  status: 'pending' | 'posted';
  type: 'income' | 'expense' | 'transfer';
}

/**
 * Represents a user's linked financial account.
 */
export interface IAccount {
  id: string; // Unique account ID in your database
  userId: string; // Foreign key linking to the IUser table
  plaidItemId: string; // The ID of the Item (bank connection) from Plaid
  plaidAccountId: string; // The unique ID for this specific account from Plaid
  
  name: string; // User-given name for the account, e.g., "My Chase Checking"
  officialName?: string; // The official name from the institution
  type: 'checking' | 'savings' | 'credit';
  balance: number; // The current balance
  lastSynced: Date; // The last time this account was successfully synced with Plaid
}